frr defaults traditional
hostname r3
no ipv6 forwarding
!
interface eth1
 description to core r2
 ip address 10.0.23.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth2
 description data centre LAN
 ip address 10.0.3.1/24
 ip ospf area 0
 ip ospf passive
exit
!
router ospf
 ospf router-id 3.3.3.3
exit
!
