frr defaults traditional
hostname r2
no ipv6 forwarding
!
ip route 10.0.1.0/24 10.0.12.1
!
interface eth1
 description branch r1
 ip address 10.0.12.2/30
exit
!
interface eth2
 description HQ server LAN
 ip address 10.0.2.1/24
exit
!
interface eth3
 description partner edge
 ip address 203.0.113.1/24
exit
!
