frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 description branch LAN
 ip address 10.0.1.1/24
exit
!
interface eth2
 description uplink to HQ (r2)
 ip address 10.0.12.1/30
exit
!
