frr defaults traditional
hostname r2
no ipv6 forwarding
!
ip route 10.0.1.0/24 10.0.12.1
ip route 10.0.12.1/32 eth1
!
interface eth1
 description transit to r1
 ip address 10.0.12.2/31
exit
!
interface eth2
 description server LAN
 ip address 10.0.3.1/24
exit
!
