frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface eth1
 description to branch r1
 ip address 10.0.12.2/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth2
 description to data centre r3
 ip address 10.0.23.1/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 2.2.2.2
exit
!
