frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 description branch LAN
 ip address 10.0.1.1/24
 ip ospf area 0
 ip ospf passive
exit
!
interface eth2
 description to core r2
 ip address 10.0.12.1/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 1.1.1.1
exit
!
